# Generated by Django 4.2.6 on 2023-10-26 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('telegram_id', models.PositiveBigIntegerField(db_index=True, verbose_name='Telegram id')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
            ],
            options={
                'verbose_name': 'Временной слот',
                'verbose_name_plural': 'Временные слоты',
            },
        ),
        migrations.CreateModel(
            name='Project_manager',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groupsapp.person')),
            ],
            options={
                'verbose_name': 'Менеджер проектов',
                'verbose_name_plural': 'Менеджеры проектов',
            },
            bases=('groupsapp.person',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groupsapp.person')),
                ('level', models.CharField(choices=[('1_newborn', 'Новички'), ('2_newborn_plus', 'Новички+'), ('3_junior', 'Джуны')], db_index=True, default='1_newborn', max_length=15, verbose_name='Уровень')),
                ('location_FE', models.BooleanField(default=False, verbose_name='Дальний Восток')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
            bases=('groupsapp.person',),
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weeks', to='groupsapp.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Неделя',
                'verbose_name_plural': 'Недели',
            },
        ),
        migrations.CreateModel(
            name='StudentProjectWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='groupsapp.week', verbose_name='Неделя')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='groupsapp.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Студенты по неделям',
                'verbose_name_plural': 'Студенты по неделям',
            },
        ),
        migrations.CreateModel(
            name='StudentProjectSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='groupsapp.timeslot', verbose_name='Временной слот')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='groupsapp.studentprojectweek', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Расписание студента',
                'verbose_name_plural': 'Расписания студентов',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='groupsapp.project', verbose_name='Проект')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='groupsapp.timeslot', verbose_name='Временной слот')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='groupsapp.project_manager', verbose_name='Менеджер проекта')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groupsapp.group', verbose_name='Группа')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groupsapp.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Студент в группе',
                'verbose_name_plural': 'Студенты в группах',
            },
        ),
        migrations.CreateModel(
            name='PMSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='groupsapp.project_manager', verbose_name='Менеджер проекта')),
            ],
            options={
                'verbose_name': 'Расписание менеджера проекта',
                'verbose_name_plural': 'Расписания менеджеров проектов',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(related_name='groups', through='groupsapp.StudentGroup', to='groupsapp.student', verbose_name='Студенты'),
        ),
    ]
