# Generated by Django 3.2.15 on 2023-10-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='actual',
            field=models.BooleanField(default=False, verbose_name='Идёт набор команд'),
        ),
    ]
