# Generated by Django 4.2.6 on 2023-10-28 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgroup',
            old_name='Group',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_group', to='groupsapp.student', verbose_name='Студент'),
        ),
    ]
