# Generated by Django 4.2.6 on 2023-10-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='actual',
            field=models.BooleanField(default=False, verbose_name='Идёт набор команд'),
        ),
    ]
