# Generated by Django 3.2.15 on 2023-10-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsapp', '0004_auto_20231030_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='trello_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Trello'),
        ),
        migrations.AddField(
            model_name='group',
            name='trello_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на Trello'),
        ),
        migrations.AlterField(
            model_name='week',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
    ]
