# Generated by Django 4.2.6 on 2023-10-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupsapp', '0002_rename_group_studentgroup_group_and_more'),
        ('groupsapp', '0005_auto_20231030_1038'),
    ]

    operations = [
    ]
